### ISSUE TITLE
Badusb to create a remote access on iPhone

### ISSUE THREAD

**Issue by Nameless410** [Peaakss/iOS-Hak5-Payloads#2]
Hi i looking for a bad usb that allows a remote access on iPhone using F0. Can you help me?

**Comment by hak5peaks** [comment]
Hi Nameless, Unfortunately there is little I can do to assist you with that task. Mainly for 2 reasons, the first being that  I only build for OMG & Hak5 devices due to the official DuckyScript support.  sorry my payloads often only work on DuckyScript compliant devices. Flipper is not.

**Comment by Nameless410** [comment]
Thank you for your answer
